# Specify the programming language
language: cpp

# Specify the environment
dist: focal   # Ubuntu 20.04 LTS

# Cache dependencies
cache:
  directories:
    - $HOME/.cache/scons
    - $HOME/mingw-w64

# Install necessary dependencies
addons:
  apt:
    packages:
      - build-essential
      - scons
      - pkg-config
      - yasm
      - zip
      - p7zip-full
      - llvm
      - clang
      - mingw-w64
      - g++-mingw-w64-x86-64

# Prepare MinGW-w64 environment
before_install:
  - sudo apt-get install -y software-properties-common
  - sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-9 100
  - sudo update-alternatives --install /usr/bin/x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-9 100

# Build stages
jobs:
  include:
    - stage: Build Godot for Windows
      script:
        # Build the editor for Windows
        - scons platform=windows target=editor use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)
        # Build the export templates
        - scons platform=windows target=template_release use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)
        - scons platform=windows target=template_debug use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)
