# Specify the programming language
language: cpp

# Specify the environment
dist: focal   # Ubuntu 20.04 LTS

# Cache dependencies
cache:
  directories:
    - $HOME/.cache/scons
    - $HOME/mingw-w64

# Install necessary dependencies
addons:
  apt:
    packages:
      - build-essential
      - scons
      - pkg-config
      - yasm
      - zip
      - p7zip-full
      - llvm
      - clang
      - mingw-w64
      - gcc-mingw-w64-x86-64-posix
      - g++-mingw-w64-x86-64-posix

# Switch to the posix variant of MinGW-w64
before_install:
  - sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
  - sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

# Build stages
jobs:
  include:
    - stage: Build Godot for Windows
      script:
        # Set environment variables for MinGW-w64
        - export PATH=$PATH:/usr/bin/x86_64-w64-mingw32/
        # Build the editor for Windows
        - scons platform=windows target=editor use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)
        # Build the export templates
        - scons platform=windows target=template_release use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)
        - scons platform=windows target=template_debug use_llvm=yes use_mingw=yes disable_exceptions=false -j$(nproc)

